Name: Mariam Siiba
Introduction: Hello, A junior in the BS IT program at GMU. I enjoy coding especially Java.
Hobbies: Coding and building websites specifically HTML, CSS, and JavaScript.
Theme: Jekyll-theme-minimal

